### ISSUE TITLE
Request for bug fix in polarizer.py

### ISSUE THREAD

**Issue by ywang002** [jdevemy/lammps-drude#3]
Dear Developers,

I am currently using the python script polarizer.py to generate the Drude particles in the data file for LAMMPS simulation. I found two bugs, one is when I followed the method by Schroeder and Steinhauser, using "python polarizer.py -k -f " to fix the charge and calculating the force constant for each type of core-Drude bond (K_D), polarizer.py doesn't calculate the K_D properly.

Another is when I used it to polarize the atoms in the modified MOFs (metal-organic frameworks), the one I am using is HKUST-1. Before the polarizer.py, the charge is neutral (total charge is -4.45E-13 e), but after it, the entire system is positively charged (around 0.0077 e). and how can I make the system neutral after polarizer.py treatment. these are the attaced files, please revise the extension to .data before open it.

[after.docx](https://github.com/user-attachments/files/17364960/after.docx)
[before.docx](https://github.com/user-attachments/files/17364961/before.docx)

I am writing this message to kindly ask if you have any suggestion or any plan to fix the problems. Thank you again for your time and all the best with your research.

Best regards
Wang

**Comment by ywang002** [comment]
Dear Developers,

I have fixed both of them.

Thanks.

Wang

**Comment by agiliopadua** [comment]
I could not open your files...

**Comment by jdevemy** [comment]
Hi,

The last version of the polarizer code is located in the paduagroup github : https://github.com/paduagroup/clandpol

Try this version and do the fix on it, it's more up to date than the version here.
Regards...
